# Generated by Django 6.0.3 on 2026-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
