# Generated by Django 6.0.3 on 2026-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
