# Generated by Django 6.0.3 on 2026-03-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommodel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='status',
        ),
    ]
