# Generated by Django 6.0.3 on 2026-03-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestModel',
            fields=[
                ('guest_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usermodel')),
            ],
            options={
                'db_table': 'guests',
            },
        ),
    ]
