# Generated by Django 6.0.3 on 2026-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='service_type',
            field=models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out'), ('Spa Session', 'Spa Session'), ('Dining', 'Dining'), ('Housekeeping', 'Housekeeping'), ('Laundry', 'Laundry'), ('Maintenance', 'Maintenance'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=20),
        ),
    ]
