# Generated by Django 6.0.3 on 2026-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Housekeeping', 'Housekeeping'), ('Maintenance', 'Maintenance')], default='Available', max_length=12),
        ),
    ]
